<!DOCTYPE html>
  <html>
    <head>
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
		<link type="text/css" rel="stylesheet" href="css/main.css">

      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>

    	<?php 
    		include('include/navbar.php')
    	?>

    <div class="wrapper">
    <div align="center"><h3>Add Student</h3></div>
		  <div class="row">
		    <form class="col s12" action="addstudentaction.php" method="post">
		      <div class="row">
		        <div class="input-field col s6">
		          <input name="firstname" id="firstname" type="text" class="validate">
		          <label for="first_name">First Name</label>
		        </div>
		        <div class="input-field col s6">
		          <input name="lastname" id="lastname" type="text" class="validate">
		          <label for="last_name">Last Name</label>
		        </div>
		      </div>
		      <div class="row">
		        <div class="input-field col s12">
		          <input name="regno" id="regno" type="text" class="validate">
		          <label for="regno">Reg No. (AutoGenerated)</label>
		        </div>
		      </div>
		      <div class="row">
		        <div class="input-field col s12">
		          <label>Gender</label>
		           <p>
				      <input name="gender" type="radio" id="gender" value="Male" />
				      <label for="gender">Male</label>
				    </p>
		           <p>
				      <input name="gender" type="radio" id="gender" value="Female" />
				      <label for="gender">Female</label>
				    </p>
		        </div>
		      </div>
		      <div class="row">
		        <div class="input-field col s12">
		          <input name="email" id="email" type="email" class="validate">
		          <label for="email">Email</label>
		        </div>
		      </div>
		      <div class="row">
		        <div class="input-field col s12">
		          <input name="contact" id="contact" type="text" class="validate">
		          <label for="contact">Contact</label>
		        </div>
		      </div>
		      <div class="row">
		        <div class="input-field col s12">
		          <input name="address" id="address" type="text" class="validate">
		          <label for="address">Address</label>
		        </div>
		      </div>

		      <div class="row">
		        <div class="input-field col s12">
		          <label>Date Of Birth</label>
		          <input name="dob" id="dob" type="text" class="datepicker">
		        </div>
		      </div>
		      <div class="row">
		        <div class="input-field col s12">
		          <label>Enroll Date</label>
		          <input name="enrolldate" id="enrolldate" type="text" class="datepicker">
		        </div>
		      </div>
		      <div class="input-field col s12">
			    <select name="roomno" id="roomno">
			      <option value="" disabled selected>Room No.</option>
			      <option value="101">101</option>
			      <option value="102">102</option>
			      <option value="103">103</option>
			      <option value="104">104</option>
			      <option value="105">105</option>
			      <option value="106">106</option>			    
			    </select>
			  </div>
			  <br>
			  <br>
			  <div class="file-field input-field">
			      <div class="btn">
			        <span>Photo</span>
			        <input name="photo" id="photo" type="file">
			      </div>
			      <div class="file-path-wrapper">
			        <input class="file-path validate" type="text">
			      </div>
			  </div>
		      <div class="input-field col s12">
			    <select name="fee" id="fee">
			      <option value="" disabled selected>Fees</option>
			      <option value="Paid">Paid</option>
			      <option value="Unpaid">Unpaid</option>
			    </select>
			  </div>

			  <input class="waves-effect waves-light btn" type="submit" name="submit">
		    	
		    </form>
		  </div>
    </div>



      <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>
      <script>
      	//Drop Down Select JS Code
      	$(document).ready(function() {
		    $('select').material_select();
		  });

      	//Date Picker JS Code
      	$('.datepicker').pickadate({
		    selectMonths: true, // Creates a dropdown to control month
		    selectYears: 15, // Creates a dropdown of 15 years to control year,
		    today: 'Today',
		    clear: 'Clear',
		    close: 'Ok',
		    closeOnSelect: false // Close upon selecting a date,
		  });
      </script>

    </body>
  </html>